server:
  port: 10080

spring:
  datasource:
    url: jdbc:mysql://47.98.161.47:3306/lab4?characterEncoding=utf8
    username: root
    password: HGFhgf555
    driver-class-name: com.mysql.cj.jdbc.Driver

#jwt配置
config:
  threshold: 20
  supplynum: 100
  salt:
  jwt:
    #加密钥匙
    secret: 012josuke456jojo
    #token有效时长，单位：秒
    expire: 3600
    #http请求头字段名称
    header: token



